import 'package:get/get.dart';

class MyTranslation extends Translations{
  @override

  Map<String, Map<String, String>> get keys => {

  "ar" : {
      "1" : "أختر اللغة" ,
      "2" : "القراءة دون اتصال" ,
      "3" : "قراءة الكتب في أي وقت وفي أي مكان، \n  وفر وقتك وبياناتك..!",
      "4" : "البحث والشراء",
      "5" : "ابحث عن الكتاب المثالي واكتشف \n الكتب الجديدة التي تهمك.",
      "6" : "أنشئ مكتبتك",
      "7" : "أضف كتبك وموضوعاتك المفضلة، \n ستظهر هنا أحدث الكتب من موضوعاتك",
      "8" : "مرحبًا بعودتك",
      "9" : "تسجيل الدخول باستخدام البريد الإلكتروني الخاص بك وكلمة المرور",
      "10" : "أدخل بريدك الإلكتروني",
      "11" : "البريد إلكتروني",
      "12" : "أدخل كلمة المرور",
      "13" : "كلمة المرور",
      "14" : "نسيت كلمة المرور",
      "15" : "تسجيل الدخول",
      "16" : "ليس لديك حساب ؟",
      "17" : "اشتراك",
      "18" : "مرحبًا بعودتك",
      "19" : "أنشئ حسابك الخاص",
      "20" : "ادخل اسم المستخدم",
      "21" : "اسم المستخدم",
      "22" : "أدخل هاتفك",
      "23" : "الهاتف",
      "24" : "لديك حساب ؟",
      "25" : "تفقد البريد الإلكتروني",
      "26" : "الرجاء إدخال عنوان بريدك الإلكتروني لتلقي رمز التحقق",
      "27" : "يفحص",
      "28" : "إعادة تعيين كلمة المرور",
      "29" : "كلمة المرور الجديدة",
      "30" : "الرجاء إدخال كلمة المرور الجديدة الخاصة بك",
      "31" : "أعد إدخال كلمة المرور",
      "32" : "حفظ",
      "33" : "رمز التحقق",
      "34" : "التحقق من الرمز",
      "35" : "الرجاء إدخال الرمز الرقمي المرسل إلى",
      "36" : "نجاح",
      "37" : "",
      "38" : "",
      "39" : "انتقل إلى تسجيل الدخول",
      "40" : "متابعة",
      "41" : "",
      "42" : "",
      "43" : "",
      "44" : "",
      "45" : "",
      "46" : "",
      "47" : "",
      "48" : "",
      "49" : "",
      "50" : "",
      "51" : "",
      "52" : "",
      "53" : "",
      "54" : "",
      "55" : "",
      "56" : "",
      "57" : "",
      "58" : "",
      "59" : "",
      "60" : "",
      "61" : "",
      "62" : "",



    },
  "en" : {
      "1" : "ْChoose Language" ,
      "2" : "Reading Offline" ,
      "3" : "Reading books at anytime anywhere , \n save your time and data..!",
      "4" : "Search & Purchase",
      "5" : "Find the perfect book for and discover \n new ones that interest you.",
      "6" : "Create Your Library",
      "7" : "Add your favourite books and topics ,  \n all latest book from your topics will appear here",
      "8" : "Welcome Back",
      "9" : "Sign In With Your Email And Password ",
      "10" : "Enter Your Email",
      "11" : "Email",
      "12" : "Enter Password",
      "13" : "Password",
      "14" : "Forget Password",
      "15" : "Sing In",
      "16" : "Don't have an account ? ",
      "17" : "Sign Up",
      "18" : "Welcome Back",
      "19" : "Create Your Own Account",
      "20" : "Enter Username",
      "21" : "Username",
      "22" : "Enter Your Phone",
      "23" : "Phone",
      "24" : "have an account ? ",
      "25" : "Check Email",
      "26" : "Please Enter Your Email Address To Recive A Verification Code",
      "27" : "Check",
      "28" : "Reset Password",
      "29" : "New Password",
      "30" : "Please Enter Your New Password",
      "31" : "Re Enter Your Password",
      "32" : "Save",
      "33" : "Verification Code",
      "34" : "Check Code",
      "35" : "Please Enter The Digit Code Sent To ",
      "36" : "Success",
      "37" : "",
      "38" : "",
      "39" : "Go To LogIn",
      "40" : "Continue",
      "41" : "",
      "42" : "",
      "43" : "",
      "44" : "",
      "45" : "",
      "46" : "",
      "47" : "",
      "48" : "",
      "49" : "",
      "50" : "",
      "51" : "",
      "52" : "",
      "53" : "",
      "54" : "",
      "55" : "",
      "56" : "",
      "57" : "",
      "58" : "",
      "59" : "",
      "60" : "",
      "61" : "",
      "62" : "",






      "3" : "",
   },
 };
}